use std::path::Path;

use common::ws::NodeCameraConfig;

pub fn generate(
    cameras: &[NodeCameraConfig],
    recordings_dir: &Path,
    api_port: u16,
    rtsp_port: u16,
) -> String {
    let mut out = format!(
        "# Generated by 64cam-node — do not edit manually\n\
         \n\
         api: true\n\
         apiAddress: :{api_port}\n\
         \n\
         rtsp: true\n\
         rtspAddress: :{rtsp_port}\n\
         \n\
         webrtc: true\n\
         webrtcAddress: :8889\n\
         webrtcAllowOrigin: '*'\n\
         \n\
         paths:\n"
    );

    for cam in cameras.iter().filter(|c| c.enabled && !c.stream_path.is_empty()) {
        let rec_path = recordings_dir
            .join(&cam.stream_path)
            .to_string_lossy()
            .replace('\\', "/");

        out.push_str(&format!(
            "  {}:\n\
             \x20   source: {}\n\
             \x20   sourceOnDemand: false\n\
             \x20   record: yes\n\
             \x20   recordPath: {rec_path}/%Y%m%d_%H%M%S\n\
             \x20   recordFormat: fmp4\n\
             \x20   recordSegmentDuration: 60s\n",
            cam.stream_path, cam.rtsp_url
        ));
    }

    if cameras.iter().all(|c| !c.enabled || c.stream_path.is_empty()) {
        out.push_str("  _placeholder:\n    source: redirect://rtsp://127.0.0.1:1\n");
    }

    out
}
